#Deployment ddo Postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgree
spec:
  selector:
    matchLabels:
      app: postgree
  template:
    metadata:
      labels:
        app: postgree
    spec:
      containers:
      - name: postgree
        image: postgres:13.16
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: fakeshop
          - name: POSTGRES_USER
            value: fakeshop
          - name: POSTGRES_PASSWORD
            value: pg1234
---
apiVersion: v1
kind: Service
metadata:
  name: postgree
spec:
  selector:
    app: postgree
  ports:
    - port: 5432
      targetPort: 5432
---
#Deployment da Aplicacao web

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
    spec:
      containers:
      - name: fakeshop
        image: guilhermecostadossantos/fake-shop:v2
        ports:
          - containerPort: 5000
        env:
          - name: DB_HOST
            value: postgree
          - name: DB_USER
            value: fakeshop
          - name: DB_PASSWORD
            value: pg1234
          - name: DB_NAME
            value: fakeshop
          - name: FLASK_APP
            value: index.py
---
apiVersion: v1
kind: Service
metadata:
  name: fakeshop
spec:
  selector:
    app: fakeshop
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer





